name: Demo Mobile Automation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack

    steps:
      - name: Code Validate
        uses: actions/checkout@v4

      - name: Config Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Definir permissões para Appium
        run: chmod +x ./node_modules/.bin/appium

      - name: Upload o BrowserStack (Android)
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: |
          response=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@app/app-demo.apk")
          app_id=$(echo $response | jq -r '.app_url')
          echo "ANDROID_APP_ID=$app_id" >> $GITHUB_ENV

      - name: Fazer upload do IPA para o BrowserStack (iOS)
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: |
          response=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@app/app-demo.ipa")
          app_id=$(echo $response | jq -r '.app_url')
          echo "IOS_APP_ID=$app_id" >> $GITHUB_ENV

      - name: Executar todos os testes
        run: npm run test:all

        with:
          branch: gh-pages
          folder: allure-report
